homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1594
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  # Customization file
  customize: !include customize.yaml

frontend:
  themes: !include_dir_merge_named themes/

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

device_tracker:
  - platform: unifi
    host: !secret unifi_controller_host
    username: !secret unifi_controller_username
    password: !secret unifi_controller_password
    verify_ssl: False
    detection_time: 30
    ssid_filter:
      - !secret unifi_tracker_ssid_filter_1
  - platform: ping
    interval_seconds: 30
    consider_home: 1200
    hosts:
      nathans_iphone: 10.10.10.101

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
